/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSegmentosRouteImport } from './routes/_authenticated/segmentos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedArquitetosRouteImport } from './routes/_authenticated/arquitetos'
import { Route as AuthenticatedAmbientesRouteImport } from './routes/_authenticated/ambientes'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos.index'
import { Route as AuthenticatedOrcamentosNovoRouteImport } from './routes/_authenticated/orcamentos.novo'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos.$id'
import { Route as AuthenticatedOrcamentosIdPdfRouteImport } from './routes/_authenticated/orcamentos.$id.pdf'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSegmentosRoute = AuthenticatedSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArquitetosRoute = AuthenticatedArquitetosRouteImport.update({
  id: '/arquitetos',
  path: '/arquitetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAmbientesRoute = AuthenticatedAmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrcamentosNovoRoute =
  AuthenticatedOrcamentosNovoRouteImport.update({
    id: '/orcamentos/novo',
    path: '/orcamentos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrcamentosIdPdfRoute =
  AuthenticatedOrcamentosIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => AuthenticatedOrcamentosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ambientes': typeof AuthenticatedAmbientesRoute
  '/arquitetos': typeof AuthenticatedArquitetosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/segmentos': typeof AuthenticatedSegmentosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/orcamentos/$id/pdf': typeof AuthenticatedOrcamentosIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ambientes': typeof AuthenticatedAmbientesRoute
  '/arquitetos': typeof AuthenticatedArquitetosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/segmentos': typeof AuthenticatedSegmentosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRouteWithChildren
  '/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/orcamentos/$id/pdf': typeof AuthenticatedOrcamentosIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ambientes': typeof AuthenticatedAmbientesRoute
  '/_authenticated/arquitetos': typeof AuthenticatedArquitetosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/segmentos': typeof AuthenticatedSegmentosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRouteWithChildren
  '/_authenticated/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/orcamentos/$id/pdf': typeof AuthenticatedOrcamentosIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ambientes'
    | '/arquitetos'
    | '/clientes'
    | '/produtos'
    | '/segmentos'
    | '/usuarios'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos/'
    | '/orcamentos/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ambientes'
    | '/arquitetos'
    | '/clientes'
    | '/produtos'
    | '/segmentos'
    | '/usuarios'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos'
    | '/orcamentos/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ambientes'
    | '/_authenticated/arquitetos'
    | '/_authenticated/clientes'
    | '/_authenticated/produtos'
    | '/_authenticated/segmentos'
    | '/_authenticated/usuarios'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/orcamentos/novo'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/orcamentos/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/segmentos': {
      id: '/_authenticated/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof AuthenticatedSegmentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arquitetos': {
      id: '/_authenticated/arquitetos'
      path: '/arquitetos'
      fullPath: '/arquitetos'
      preLoaderRoute: typeof AuthenticatedArquitetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ambientes': {
      id: '/_authenticated/ambientes'
      path: '/ambientes'
      fullPath: '/ambientes'
      preLoaderRoute: typeof AuthenticatedAmbientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orcamentos/novo': {
      id: '/_authenticated/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof AuthenticatedOrcamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orcamentos/$id/pdf': {
      id: '/_authenticated/orcamentos/$id/pdf'
      path: '/pdf'
      fullPath: '/orcamentos/$id/pdf'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdPdfRouteImport
      parentRoute: typeof AuthenticatedOrcamentosIdRoute
    }
  }
}

interface AuthenticatedOrcamentosIdRouteChildren {
  AuthenticatedOrcamentosIdPdfRoute: typeof AuthenticatedOrcamentosIdPdfRoute
}

const AuthenticatedOrcamentosIdRouteChildren: AuthenticatedOrcamentosIdRouteChildren =
  {
    AuthenticatedOrcamentosIdPdfRoute: AuthenticatedOrcamentosIdPdfRoute,
  }

const AuthenticatedOrcamentosIdRouteWithChildren =
  AuthenticatedOrcamentosIdRoute._addFileChildren(
    AuthenticatedOrcamentosIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAmbientesRoute: typeof AuthenticatedAmbientesRoute
  AuthenticatedArquitetosRoute: typeof AuthenticatedArquitetosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedSegmentosRoute: typeof AuthenticatedSegmentosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRouteWithChildren
  AuthenticatedOrcamentosNovoRoute: typeof AuthenticatedOrcamentosNovoRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAmbientesRoute: AuthenticatedAmbientesRoute,
  AuthenticatedArquitetosRoute: AuthenticatedArquitetosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedSegmentosRoute: AuthenticatedSegmentosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRouteWithChildren,
  AuthenticatedOrcamentosNovoRoute: AuthenticatedOrcamentosNovoRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
