// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Valores de produção — chave anon pública, seguro manter no código.
const FALLBACK_URL = "https://ccdquqmuxvcadveaidyc.supabase.co";
const FALLBACK_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZHF1cW11eHZjYWR2ZWFpZHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyMzY3MTEsImV4cCI6MjA5NTgxMjcxMX0.hC_BiyjHJCxMzzscCS74rMPvm1uvbvsPGv8l8Cg_a_c";

function createSupabaseClient() {
  // Ordem de resolução:
  // 1. import.meta.env.VITE_* — injetado pelo Vite em build-time (quando a var está no env de build)
  // 2. process.env.VITE_*     — runtime via nodejs_compat (quando mapeado pelo Workers)
  // 3. Fallback hardcoded     — garante funcionamento no Cloudflare Workers onde nenhuma das
  //                             opções acima está disponível (vars do wrangler.jsonc são bindings
  //                             de runtime acessíveis via env.VAR, não via process.env)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.VITE_SUPABASE_URL ||
    FALLBACK_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    FALLBACK_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

